version: '3.8'
services:
  redis:
    image: "redis:alpine"
    container_name: flask_auth_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
    driver: local 